spring:
  application:
    name: ass
  
  datasource:
    driver-class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/loan
    username: postgres
    password: postgres
 
  jpa :  
    hibernate:
      ddl-auto: update
