spring:
  application:
    name: ASSIGNMENTINVENTORYMVC

  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp

server:
  port: 9080